-- Ejecuta este comando en el editor SQL de Supabase para añadir soporte a la tabla de obras
CREATE TABLE IF NOT EXISTS work_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients (id) ON DELETE CASCADE,
  hours REAL,
  material_description TEXT,
  material_price REAL
);

-- Deshabilitar RLS para que el backend pueda escribir (como hicimos con las otras tablas)
ALTER TABLE work_items DISABLE ROW LEVEL SECURITY;
