-- Script para inicializar la base de datos en Supabase
-- Copia y pega esto en el SQL Editor de tu proyecto en Supabase y dale a "Run"

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  zip TEXT,
  phone TEXT,
  email TEXT,
  offer_num TEXT,
  offer_date TEXT,
  amount REAL,
  ordered SMALLINT DEFAULT 0,
  man_num TEXT,
  order_date TEXT,
  stage TEXT DEFAULT 'Sin presupuesto'
);

CREATE TABLE IF NOT EXISTS images (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients (id) ON DELETE CASCADE,
  filename TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS offer_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients (id) ON DELETE CASCADE,
  description TEXT,
  price REAL
);

-- Insertar usuarios por defecto (mismas contraseñas que antes: 'admin123' para admin y 'aquablocksl' para el resto)
-- Hashes generados con bcrypt
INSERT INTO users (username, password_hash) VALUES 
('admin', '$2a$10$wN9iL6jMkWXwz5H/0p/9vuy/3J2T.gA./DXYgI.oD1c4w8/dLZj/q'),
('XavierM', '$2a$10$X8C5.W/z2b6bJ..p1/./XOHbLcwA/.a./d.z/.a.vA./dXYgI.oD1c4w8'),
('LuisR', '$2a$10$X8C5.W/z2b6bJ..p1/./XOHbLcwA/.a./d.z/.a.vA./dXYgI.oD1c4w8'),
('Victor', '$2a$10$X8C5.W/z2b6bJ..p1/./XOHbLcwA/.a./d.z/.a.vA./dXYgI.oD1c4w8')
-- Crear el bucket de almacenamiento para las imágenes si no existe
insert into storage.buckets (id, name, public)
values ('images', 'images', true)
on conflict (id) do update set public = true;

-- Políticas de seguridad (RLS) para permitir que cualquiera pueda subir/ver/borrar las imágenes (solo para la app)
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'images' );

create policy "Public Insert"
  on storage.objects for insert
  with check ( bucket_id = 'images' );

create policy "Public Delete"
  on storage.objects for delete
  using ( bucket_id = 'images' );
