-- Script para inicializar la base de datos en Supabase
-- Copia y pega esto en el SQL Editor de tu proyecto en Supabase y dale a "Run"

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  zip TEXT,
  phone TEXT,
  email TEXT,
  offer_num TEXT,
  offer_date TEXT,
  amount REAL,
  ordered SMALLINT DEFAULT 0,
  man_num TEXT,
  order_date TEXT,
  stage TEXT DEFAULT 'Sin presupuesto'
);

CREATE TABLE IF NOT EXISTS images (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients (id) ON DELETE CASCADE,
  filename TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS offer_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients (id) ON DELETE CASCADE,
  description TEXT,
  price REAL
);
